---
# This should be a secure and secret value
SNUEUE_REDDIT_USER_AGENT: Snueue development testing by \u\<yourusername>
# This should be a secure and secret value
SNUEUE_SECRET_KEY: secret
# To connect to reddit via oauth, you'll need to create an app on reddit.com/prefs/apps
# More info: https://github.com/reddit/reddit/wiki/OAuth2
SNUEUE_REDDIT_CLIENT_ID:
SNUEUE_REDDIT_CLIENT_SECRET:
...
