preferred_syntax = :sass
http_path = '/'
css_dir = 'build/'
sass_dir = 'stylesheets'
images_dir = 'images'
javascripts_dir = 'javascripts'
relative_assets = true
line_comments = true
# output_style = :compressed
